[workspace]
resolver = "2"

members = [
    "crates/poke_engine",
    "crates/poke_core",
    "examples/tallgrass_demo"
    ]

[workspace.package]
edition = "2021"


[workspace.dependencies]
bevy = "0.17.3"
fastrand = "2.3.0"