[package]
name = "tallgrass_demo"
version = "0.1.0"
edition.workspace = true

[dependencies]
bevy.workspace = true
fastrand.workspace = true
serde.workspace = true
serde_json.workspace = true
poke_engine ={ path = "../../crates/poke_engine" }
